### ISSUE TITLE
When my html string contains an image, RichText renders at an incorrect height because the image hasn't loaded yet

### ISSUE THREAD

**Issue by panghujiajia** [NuPlay/RichText#38] opened 2023-07-22 17:28 UTC

**Comment by NuPlay** [comment] 2023-07-30 20:19
Doesn't the frame change after the image loads?

**Comment by NuPlay** [comment] 2023-09-17 14:27
Thank you for bringing this issue to our attention. I've looked into the problem and identified the root cause.

I'm currently in the process of restructuring the library, and I'll make sure to address this issue as part of that work.

I apologize for not being as active in maintaining the library recently; it's been a busy time for me.
However, I'm committed to resolving this as quickly as possible.

**Comment by panghujiajia** [comment] 2023-09-18 11:38
thanks!

**Comment by axiel7** [comment] 2024-04-05 09:20
I have a similar problem where RichText ignores the `width` value of the `img`. Maybe this is related or should I open a separate issue?

**Comment by paranoidjk** [comment] 2024-11-30 10:38
@NuPlay  I also encountered this issue, and I submitted a PR to fix it https://github.com/NuPlay/RichText/pull/54

**Closed** 2024-11-30 15:21 UTC
