### ISSUE TITLE
runtime failure: force unwrap

### ISSUE THREAD

**Issue by roccodebellis** [NuPlay/RichText#32] opened 2023-05-02 07:58 UTC
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/37178885/235607524-1dcc3f9d-16ab-47ae-8f2f-bf1a2e1a2179.png">

This happen on those circumstances where the view will be unallocated before the content was uploaded, there is a crash due to force unwrap of variable `height`. 
Since we don't want to risk an accident, can i suggest to don't force unwrap an optional only to find that it could be void.

**Comment by NuPlay** [comment] 2023-05-02 16:42
Thanks for pointing out the issue. We have addressed the crash caused by force unwrapping the height variable in PR #33 and released the fix in version v2.2.1. The updated code now handles the optional value safely.

Please update to v2.2.1 to see the changes. If you have any further concerns or issues, feel free to let us know.

Closing this issue as it has been resolved in v2.2.1.

**Comment by NuPlay** [comment] 2023-05-02 16:42
Thanks for pointing out the issue. I have addressed the crash caused by force unwrapping the height variable in PR #33 and released the fix in version v2.2.1. The updated code now handles the optional value safely.

Please update to v2.2.1 to see the changes. If you have any further concerns or issues, feel free to let us know.

Closing this issue as it has been resolved in v2.2.1.

**Closed by NuPlay** 2023-05-02 16:42 UTC

**Comment by NuPlay** [comment] 2023-05-02 16:46
Thank you for pointing out the issue. I have addressed it in PR #33 and released the fix in version v2.2.1. Please update to v2.2.1 to see the changes.

I appreciate your valuable feedback. If you have any further concerns or issues, feel free to let me know.

Closing this issue as it has been resolved in v2.2.1.
